
language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_whitespace"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+" 

policies:
  - name: FallbackPolicy
    nlu_threshold: 0.7
    core_threshold: 0.2
    fallback_action_name: "utter_default"
  - name: MemoizationPolicy
    max_history: 10
  - name: FormPolicy
  - name: MappingPolicy